---
title: "R Notebook"
output: html_notebook
---
$$\begin{align*}
f(x|y) &\propto y e^{-yx}, ~~0<x<B<<\infty \\
f(y|x) &\propto x e^{-xy}, ~~0<y<B<<\infty \\
\end{align*}$$

```{r}
itexp <- function(u, m, t) { -log(1-u*(1-exp(-t*m)))/m }

rtexp <- function(n, m, t) { itexp(runif(n), m, t) }

hist(rtexp(1000, 1, 5), probability = 1)
```
```{r}
k = 15
m = 1000
B = 5

y_draws = rep(0, m)
x_draws = rep(0, m)
x_temp = 2
y_temp = 2

for (i in 1:m) {
  for (j in 1:k) {
    x_temp = rtexp(1, y_temp, B)
    y_temp = rtexp(1, x_temp, B)
  }
  x_draws[i] = x_temp
  y_draws[i] = y_temp
}

{par(mfrow = c(1, 2))
hist(x_draws, probability = 1)
hist(rtexp(1000, 1, 5), probability = 1)}
```
```{r}
X = rep(0, 500)
Y = rep(0, 500)

k = 15

for (i in 1:500) {
  x = rep(1, k)
  y = rep(1, k)

  for (j in 2:k) {
    temp_x = 6
    while(temp_x>5) {
      x[j] = rexp(1,y[j-1])
      temp_x = x[j]
    }

    temp_y = 6
    while(temp_y>5) {
      y[j] = rexp(1,x[j])
      temp_y = y[j]
    }     
  }

  X[i] = x[k]
  Y[i] = y[k] 
}
print(max(X))
print(max(Y))

hist(X, breaks=40, freq=F)
```

